apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-configmap
data:
  config.custom.toml: |
{{ .Values.config | indent 4 }}
  genesis.custom.json: |
{{ .Values.genesis | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-password
data:
  password: |
{{ .Values.password | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-key
data:
  key.json: |
{{ .Values.key | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-env-configmap
data:
  {{- toYaml .Values.env | nindent 2 }}