---
{{ if .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geth.fullname" . }}-password
stringData:
  password: |
{{ .Values.password | indent 4 }}
{{- end }}

---
{{ if .Values.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geth.fullname" . }}-key
stringData:
  key.json: |
{{ .Values.key | indent 4 }}
{{- end }}
